// vue-app/src/App.vue
<script setup>
import Icon from "./Icon.vue";
import { ref, watch, onMounted } from "vue";

const tasks = ref([]);
const inputContent = ref("");

const addTask = () => {

  if (inputContent.value.trim() === "" || inputContent.value === null)
    return;
    
    tasks.value.push({
        id: uuidv4(),
        name: inputContent.value,
        status: false,
    });
    
    inputContent.value = "";
};

const deleteTask = (id) => {
    tasks.value = tasks.value.filter((t) => t.id !== id);
};

function clearAll() {
    tasks.value = [];
}

function uuidv4() {
  return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, (c) =>
    (c ^ (crypto.getRandomValues(new Uint8Array(1))[0] & (15 >> (c / 4)))).toString(16)
  );
}

watch(tasks, (newVal) => {
    localStorage.setItem("tasks", JSON.stringify(newVal));
}, { deep: true });

onMounted(() => {
    tasks.value = JSON.parse(localStorage.getItem('tasks')) || []
})

</script>

<template>
  <div class="wrapper">
    <form @submit.prevent="addTask" class="task-input">
      <Icon />
      <input type="text" placeholder="Add a new task" v-model="inputContent" />
    </form>
    <div class="controls">
      <button v-on:click="clearAll" :class="`clear-btn ${tasks.length ? 'active' : ''}`">
        Clear All
      </button>
    </div>
    <ul class="task-box">

      <span v-if="tasks.length === 0">You don't have any task here</span>

      <li v-for="task in tasks" v-bind:key="task" class="task">
        <label :for="task.id">
          <input :id="task.id" type="checkbox" v-model="task.status" />
          <p :class="`${task.status ? 'checked' : ''}`">{{ task.name }}</p>
        </label>
        <div>
          <button v-on:click="() => deleteTask(task.id)">Delete</button>
        </div>
      </li>
    </ul>
  </div>
</template>

<style scoped>
</style>

// svelte-app/src/App.svelte
<script>
    import icon from "./bars-icon.svg";
    import { onMount } from "svelte";

    let tasks = [];
    let taskText = "";

    onMount(() => {
        tasks = JSON.parse(localStorage.getItem("tasks")) || [];
    });

    function addTask() {

        if (taskText.trim() === "" || taskText === null)
            return;

        tasks = [
            ...tasks,
            {
                id: uuidv4(),
                name: taskText,
            },
        ];
        localStorage.setItem("tasks", JSON.stringify(tasks));
        taskText = "";
    }

    function deleteTask(id) {
        tasks = tasks.filter((t) => t.id !== id);
        localStorage.setItem("tasks", JSON.stringify(tasks));
    }

    function clearAll() {
        tasks = [];
        localStorage.setItem("tasks", JSON.stringify([]));
    }

    function updateStatus(id) {
        tasks = tasks.map((task) => {
            if (task.id === id) {
                task.status =
                    task.status == "completed" ? "pending" : "completed";
            }

            return task;
        });
        localStorage.setItem("tasks", JSON.stringify(tasks));
    }

    function uuidv4() {
        return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, (c) =>
            (
                c ^
                (crypto.getRandomValues(new Uint8Array(1))[0] & (15 >> (c / 4)))
            ).toString(16)
        );
    }
</script>

<div class="wrapper">
    <form on:submit|preventDefault={addTask} class="task-input">
        <img src={icon} alt="icon" />
        <input bind:value={taskText} type="text" placeholder="Add a new task" />
    </form>
    <div class="controls">
        <button
            on:click={clearAll}
            class={`clear-btn ${tasks.length ? "active" : ""}`}
            >Clear All</button
        >
    </div>

    <ul class="task-box">
        {#if tasks.length === 0}
            <span>You don't have any task here</span>
        {:else}
            {#each tasks as task}
                <li class="task">
                    <label for={task.id}>
                        <input
                            type="checkbox"
                            id={task.id}
                            on:change={() => updateStatus(task.id)}
                            checked={task.status === "completed"}
                        />
                        <p class={task.status === "completed" ? "checked" : ""}>
                            {task.name}
                        </p>
                    </label>
                    <div>
                        <button on:click={() => deleteTask(task.id)}
                            >Delete</button
                        >
                    </div>
                </li>
            {/each}
        {/if}
    </ul>
</div>
