// react-app/src/App.jsx
import React from "react";
import icon from './bars-icon.svg'

function uuidv4() {
    return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, c =>
        (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
    );
}

function App(props) {

    const input = React.useRef(null)

    const [tasks, setTasks] = React.useState(() => {
        return JSON.parse(localStorage.getItem("tasks")) || [];
    });

    React.useEffect(() => {
        localStorage.setItem("tasks", JSON.stringify(tasks));
    }, [tasks]);

    function updateStatus(id) {

        let task = tasks.find(t => t.id === id);
        task.status = task.status === "completed" ? "pending" : "completed"

        setTasks((prevState) => {
            return prevState.map(x => {
                if (x.id === task.id)
                    x = task;

                return x;
            })
        })
    }

    function deleteTask(id) {
        let filteredTask = tasks.filter(t => t.id !== id);
        setTasks(filteredTask)
    }

    function clearAll() {
        setTasks([])
    }

    function addTask(event) {

        event.preventDefault();

        if (!input.current || input.current.value === "" || input.current.value === null)
            return;

        let newTask = {
            id: uuidv4(),
            name: input.current.value,
            status: "pending"
        }

        setTasks((prevState) => {
            return [
                ...prevState,
                newTask
            ]
        })

        input.current.value = '';
    }

    function renderTasks() {

        let filteredTask =
            tasks.map((t, idx) => {
                let completed = t.status === "completed" ? "checked" : "";
                return (
                    <li key={idx} className="task">
                        <label htmlFor={idx}>
                            <input type="checkbox" id={idx} onChange={() => updateStatus(t.id)} checked={completed} />
                            <p className={completed}>{t.name}</p>
                        </label>
                        <div>
                            <button onClick={() => deleteTask(t.id)}>Delete</button>
                        </div>
                    </li>
                );
            })

        return filteredTask.length > 0 ? filteredTask : <span>You don't have any task here</span>;

    }


    return (
        <div className="wrapper">
            <form className="task-input" onSubmit={addTask}>
                <img src={icon} alt="icon" />
                <input type="text" placeholder="Add a new task" ref={input} />
            </form>
            <div className="controls">
                <button onClick={clearAll} className={`clear-btn ${tasks.length ? "active" : ""}`}>Clear All</button>
            </div>
            <ul className="task-box">
                {
                    renderTasks()
                }
            </ul>
        </div>
    );
}

export default App;

// svelte-app/src/App.svelte
<script>
    import icon from "./bars-icon.svg";
    import { onMount } from "svelte";

    let tasks = [];
    let taskText = "";

    onMount(() => {
        tasks = JSON.parse(localStorage.getItem("tasks")) || [];
    });

    function addTask() {

        if (taskText.trim() === "" || taskText === null)
            return;

        tasks = [
            ...tasks,
            {
                id: uuidv4(),
                name: taskText,
            },
        ];
        localStorage.setItem("tasks", JSON.stringify(tasks));
        taskText = "";
    }

    function deleteTask(id) {
        tasks = tasks.filter((t) => t.id !== id);
        localStorage.setItem("tasks", JSON.stringify(tasks));
    }

    function clearAll() {
        tasks = [];
        localStorage.setItem("tasks", JSON.stringify([]));
    }

    function updateStatus(id) {
        tasks = tasks.map((task) => {
            if (task.id === id) {
                task.status =
                    task.status == "completed" ? "pending" : "completed";
            }

            return task;
        });
        localStorage.setItem("tasks", JSON.stringify(tasks));
    }

    function uuidv4() {
        return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, (c) =>
            (
                c ^
                (crypto.getRandomValues(new Uint8Array(1))[0] & (15 >> (c / 4)))
            ).toString(16)
        );
    }
</script>

<div class="wrapper">
    <form on:submit|preventDefault={addTask} class="task-input">
        <img src={icon} alt="icon" />
        <input bind:value={taskText} type="text" placeholder="Add a new task" />
    </form>
    <div class="controls">
        <button
            on:click={clearAll}
            class={`clear-btn ${tasks.length ? "active" : ""}`}
            >Clear All</button
        >
    </div>

    <ul class="task-box">
        {#if tasks.length === 0}
            <span>You don't have any task here</span>
        {:else}
            {#each tasks as task}
                <li class="task">
                    <label for={task.id}>
                        <input
                            type="checkbox"
                            id={task.id}
                            on:change={() => updateStatus(task.id)}
                            checked={task.status === "completed"}
                        />
                        <p class={task.status === "completed" ? "checked" : ""}>
                            {task.name}
                        </p>
                    </label>
                    <div>
                        <button on:click={() => deleteTask(task.id)}
                            >Delete</button
                        >
                    </div>
                </li>
            {/each}
        {/if}
    </ul>
</div>
